[template]
cargo_generate_version = ">=0.17.4"
ignore = [".git", ".github/dependabot.yml", ".github/workflows/ci_docker.yml", ".github/workflows/ci.yml", ".github/workflows/issue_handler.yml", "README.md"]

[hooks]
pre = ["pre-script.rhai"]

[placeholders.chip]
type = "string"
prompt = "Which MCU to target?"
# TODO: Auto-generate the extended list (i.e. from stm32-data)
choices = ["stm32f411ce", "esp32c3"]
default = "stm32f411ce"
