[target.'cfg(all(target_arch = "{{ arch }}", target_os = "none"))']
# if use probe-rs capable debugger use this:
# runner = "probe-rs run --chip {{ probe_chip }}"
{% if chip contains "stm32" -%}
runner = "cargo xtask gdb"
{% endif -%}
{% if chip contains "esp32" -%}
runner = "espflash flash --monitor -L defmt"
{% endif -%}


[build]
target = "{{ rust_target }}"
rustflags = [
{% if chip contains "esp32" -%}
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
{% endif -%}
{% if chip contains "stm32" -%}
  "-C", "link-arg=-Tlink.x",
{% endif -%}
  "-C", "link-arg=-Tdefmt.x",
]

[alias]
xtask = "run --manifest-path xtask/Cargo.toml --target x86_64-unknown-linux-gnu --"

[env]
DEFMT_LOG = "info"
